name: Pipeline Car Prediction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Teste
      run: coverage run novos_dados.py
      
    - name: Relatório do Teste  
      run: coverage report -m 


    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-crddunrtq21c73d2fg50
        api-key: rnd_AEkH5UZCPxUdARznEAevOzB4obY3
